version: "3"
services:
  postgres:
    image: "postgres:11"
    container_name: "postgres"
    ports:
      - "5432:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: pwd123
      POSTGRES_USER: postgresuser
  postgres-api:
    image: resulguldibi/postgres-api
    container_name: postgres-api
    restart: always
    depends_on:
      - postgres
    links:
      - postgres  
    ports:
      - 8080:8080
volumes:
  my_dbdata:
